Repository aspirepress/aspireupdate, pull requests merged in 2024-11, with the labels that each got.

#87 Add PHPUnit.
  .github/workflows/phpunit-tests.yml
  .gitignore
  bin/install-wp-tests.sh
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/AdminSettings/AdminSettings_GetSettingTest.php
  tests/bootstrap.php
Labels: enhancement

#92 `Workflows`: Fix PHP version and add more workflow triggers.
  .github/workflows/phpunit-tests.yml
Labels: enhancement

#97 `Tests`: Add default coverage settings.
  .gitignore
  phpunit.xml.dist
Labels: testing

#111 Added German Translation
  .gitignore
  languages/AspireUpdate-de_DE.I10n.php
  languages/AspireUpdate-de_DE.mo
  languages/AspireUpdate-de_DE.po
Labels: i18n

#117 Voltron has landed.
  assets/css/aspire-update.css
  includes/class-admin-settings.php
Labels: documentation

#102 add multisite support
  aspire-update.php
  includes/class-admin-settings.php
Labels: enhancement

#123 Add `.editorconfig`.
  .editorconfig
Labels: documentation

#121 create zip with each new tagged release
  .gitattributes
  .github/workflows/releases.yml
Labels: enhancement

#98 Updating Playground-ready from main
  .editorconfig
  .gitattributes
  .github/workflows/phpunit-tests.yml
  .github/workflows/releases.yml
  .gitignore
  aspire-update.php
  assets/css/aspire-update.css
  assets/js/aspire-update.js
  bin/install-wp-tests.sh
  composer.json
  composer.lock
  includes/class-admin-settings.php
  includes/class-controller.php
  includes/class-debug.php
  includes/class-themes-screens.php
  languages/AspireUpdate-de_DE.I10n.php
  languages/AspireUpdate-de_DE.mo
  languages/AspireUpdate-de_DE.po
  languages/AspireUpdate-fr_FR.l10n.php
  languages/AspireUpdate-fr_FR.mo
  languages/AspireUpdate-fr_FR.po
  languages/AspireUpdate-zh_TW.l10n.php
  languages/AspireUpdate-zh_TW.mo
  languages/AspireUpdate-zh_TW.po
  languages/AspireUpdate.pot
  phpunit.xml.dist
  tests/AdminSettings/AdminSettings_GetSettingTest.php
  tests/bootstrap.php
Labels: enhancement

#126 Clean up after `.editorconfig` was added to the repository.
  assets/css/aspire-update.css
  assets/js/aspire-update.js
  assets/playground/blueprint.json
  composer.json
  includes/class-themes-screens.php
  languages/AspireUpdate-de_DE.I10n.php
  languages/AspireUpdate-zh_TW.l10n.php
  readme.txt
  tests/AdminSettings/AdminSettings_GetSettingTest.php
Labels: documentation, enhancement

#127 Add coding standard.
  .cache/.gitkeep
  .github/workflows/coding-standards.yml
  .gitignore
  composer.json
  composer.lock
  includes/autoload.php
  includes/class-admin-settings.php
  includes/class-api-rewrite.php
  includes/class-controller.php
  includes/class-debug.php
  includes/class-plugins-screens.php
  includes/class-themes-screens.php
  phpcs.xml.dist
  tests/bootstrap.php
Labels: documentation, enhancement

#129 Continue to sync playground-ready with newest PRs on main
  .cache/.gitkeep
  .github/workflows/coding-standards.yml
  .gitignore
  assets/css/aspire-update.css
  assets/js/aspire-update.js
  assets/playground/blueprint.json
  composer.json
  composer.lock
  includes/autoload.php
  includes/class-admin-settings.php
  includes/class-api-rewrite.php
  includes/class-controller.php
  includes/class-debug.php
  includes/class-plugins-screens.php
  includes/class-themes-screens.php
  languages/AspireUpdate-de_DE.I10n.php
  languages/AspireUpdate-zh_TW.l10n.php
  phpcs.xml.dist
  readme.txt
  tests/AdminSettings/AdminSettings_GetSettingTest.php
  tests/bootstrap.php
Labels: enhancement

#119 Added License File
  LICENSE.md
  aspire-update.php
  composer.json
  readme.txt
Labels: documentation

#145 Adding new Spanish translation
  languages/AspireUpdate-es_ES.po
Labels: i18n

#78 add Git Updater integration
  aspire-update.php
Labels: documentation

#99 Asirota/add issue template
  .github/ISSUE_TEMPLATE/BugReport.yml
  .github/ISSUE_TEMPLATE/FeatureRequest.yml
  .github/ISSUE_TEMPLATE/config.yml
  readme.txt
Labels: documentation

#158 Add Site Health option
  .github/ISSUE_TEMPLATE/BugReport.yml
Labels: documentation

#154 Updated the German Translation
  .DS_Store
  languages/AspireUpdate-de_DE.mo
  languages/AspireUpdate-de_DE.po
Labels: i18n

#150 Updating Spanish translations
  languages/AspireUpdate-es_ES.po
Labels: i18n

#168 Clear Logs and View Logs Functionality Added
  assets/css/aspire-update.css
  assets/js/aspire-update.js
  includes/class-admin-settings.php
  includes/class-controller.php
  includes/class-debug.php
  includes/views/page-admin-settings.php
Labels: enhancement

#177 Settings Saved Notice
  includes/class-admin-settings.php
Labels: enhancement

#185 added changelog
  README.md
Labels: documentation

#199 update afragen/translations-updater with error caching/logging
  composer.lock
  vendor/afragen/translations-updater/CHANGES.md
  vendor/afragen/translations-updater/README.md
  vendor/afragen/translations-updater/composer.json
  vendor/afragen/translations-updater/src/Translations_Updater/API.php
  vendor/afragen/translations-updater/src/Translations_Updater/Language_Pack.php
  vendor/afragen/translations-updater/src/Translations_Updater/Language_Pack_API.php
Labels: bug
